server:
  port: 8080

# Configurações do Banco de dados
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# Configurações do Token JWT
api:
  security:
    token:
      user:
        secret: ${JWT_USER_SECRET:SENHA_SECRETA_PARA_VALIDAR_AUTENTICACAO_DO_USUARIO}
      apigateway:
        secret: ${JWT_GATEWAY_SECRET:SENHA_SECRETA_PARA_VALIDAR_API_GATEWAY}
      mscadastro:
        secret: ${JWT_MS_CADASTRO_SECRET:SENHA_SECRETA_PARA_VALIDAR_MS_CADASTRO}
  gateway:
    issuer: API GATEWAY SPORTEASE UFPR
  user:
    issuer: USER ISSUER SPORTEASE UFPR
  mscadastro:
    issuer: API MS CADASTRO SPORTEASE UFPR

# URLs
url:
  ms:
    cadastros:
      adm: ${MS_CADASTROS_ADM_URL:http://localhost:8081/adm}
      clientes: ${MS_CADASTROS_CLIENTES_URL:http://localhost:8081/clientes}
      espacos_esportivos: ${MS_CADASTROS_ESPACOES_ESPORTIVOS_URL:http://localhost:8081/espacos-esportivos}
      esportes: ${MS_CADASTROS_ESPORTES_URL:http://localhost:8081/esportes}
      usuarios: ${MS_CADASTROS_USUARIOS_URL:http://localhost:8081/usuarios}
    locacoes: ${MS_LOCACOES_URL:http://localhost:8082/locacoes}
